# -*- coding: utf-8 -*-
# file: basis/relativity.py

# This code is part of Mandacaru.
# MIT License
#
# Copyright (c) 2026 Leandro Seixas Rocha <leandro.rocha@ilum.cnpem.br>

r"""Scalar-relativistic and Dirac radial atoms.

The non-relativistic radial equation
(:func:`~mandacaru.basis.atomic_solver.solve_radial`) is what every basis and
pseudopotential in Mandacaru was built from.  It is a poor description of a
heavy atom's core: the :math:`1s` shell of gold moves by tens of Hartree, the
valence :math:`s` levels contract and the :math:`d` levels expand, and the
:math:`p`, :math:`d` and :math:`f` channels split by the spin-orbit interaction.
This module supplies all three levels of theory through **one** radial operator.

One equation, three theories
----------------------------

Eliminating the small component from the Dirac radial pair is *exact*.  Writing
:math:`P = rg` for the large component and

.. math::

    M(r) = 1 + \frac{\varepsilon - V(r)}{2c^2}

(the local relativistic mass enhancement), the pair collapses to

.. math::

    P'' - \frac{l(l+1)}{r^2}P
        - \frac{M'}{M}\Big(P' + \frac{\kappa}{r}P\Big)
        = -2M(\varepsilon - V)P ,

where :math:`\kappa = -(l+1)` for :math:`j = l+\tfrac12` and :math:`\kappa = +l`
for :math:`j = l-\tfrac12`.  The angular momentum enters twice: through
:math:`\kappa(\kappa+1) = l(l+1)`, which is **the same for both** :math:`j`, and
through the lone :math:`\kappa M'P/(Mr)` term -- *that* term, and only that term,
is the spin-orbit interaction.

The three theories are then three values of one parameter:

=====================  =========================  ===============================
Theory                 :math:`\kappa`             Recovered by
=====================  =========================  ===============================
Non-relativistic       (any; :math:`M\equiv1`)    :math:`c\to\infty`
Scalar-relativistic    :math:`\langle\kappa\rangle = -1`  averaging over :math:`j`
Dirac                  :math:`-(l+1)` or :math:`+l`  the physical value
=====================  =========================  ===============================

The scalar-relativistic value is not a fit or a convention: the
:math:`(2j+1)`-weighted average of :math:`\kappa` over :math:`j = l\pm\tfrac12`
is

.. math::

    \langle\kappa\rangle =
      \frac{-(l+1)(2l+2) + l\,(2l)}{(2l+2) + 2l} = -1

for **every** :math:`l`, which is why Koelling and Harmon's equation
(J. Phys. C **10**, 3107 (1977)) has no :math:`l` dependence in its spin-orbit
term.  Setting :math:`\kappa = -1` therefore drops spin-orbit coupling while
keeping the mass-velocity and Darwin effects in full.  For :math:`l = 0` there
is only one :math:`j`, and :math:`\kappa = -1` *is* its physical value -- so for
s states the scalar-relativistic equation is the exact Dirac equation, which is
how ``test/basis/test_relativity.py`` pins the implementation against the
closed-form hydrogenic Dirac spectrum.

Why this form and not a first-order integration
-----------------------------------------------

Substituting :math:`P = M^{1/2}W` cancels the first-derivative term identically
(the :math:`M'` generated by differentiating :math:`M^{1/2}` is exactly the one
already there), leaving

.. math::

    W'' = \Big[\frac{l(l+1)}{r^2} + \frac{\kappa M'}{Mr}
              - \frac{M''}{2M} + \frac{3(M')^2}{4M^2}
              + 2M(V - \varepsilon)\Big] W .

That has the shape :math:`W'' = fW` that
:func:`~mandacaru.pseudopotentials.oncv.numerov_outward` already integrates, so
scattering states and logarithmic derivatives come for free
(:func:`relativistic_f`), and the bound-state problem stays a **symmetric
tridiagonal eigenproblem** -- :math:`\tilde H = M^{-1/2}AM^{-1/2}` with
eigenvalue :math:`2\varepsilon` and eigenvector :math:`P` itself.  A
two-component Runge-Kutta shoot would have cost a root-find per subshell per
SCF iteration; this keeps the self-consistent atom as fast as it was.

:math:`M` depends on :math:`\varepsilon`, so the eigenproblem is solved two or
three times per state with :math:`M` rebuilt from the previous eigenvalue
(:func:`solve_radial_relativistic`); it converges geometrically because the
relativistic shift is :math:`O(c^{-2})` of the level itself.

Normalization
-------------

States are normalized :math:`\int P^2\,dr = 1`, the convention the
non-relativistic solver and everything downstream of it already use.  The small
component's share of the norm, :math:`\int F^2 dr = O((Z\alpha)^2)`, is
therefore not counted -- 5e-5 of the charge for oxygen, 4e-3 for gold, and
concentrated within the core radius where a pseudopotential replaces the
density anyway.  :func:`small_component` returns :math:`F` for the cases that
want it.
"""

from __future__ import annotations

import numpy as np
from scipy.linalg import eigh_tridiagonal

#: Speed of light in atomic units -- the inverse fine-structure constant.
#: CODATA 2022: ``1/alpha = 137.035999177(21)``.
SPEED_OF_LIGHT = 137.035999177

#: The levels of theory :func:`solve_radial_relativistic` accepts.
TREATMENTS = ("none", "scalar", "dirac")

#: ``kappa`` of the scalar-relativistic (j-averaged) equation, for every l.
SCALAR_KAPPA = -1

#: Convergence of the ``M(epsilon)`` iteration, relative to the level itself
#: (with an absolute floor of the same size).  The iteration contracts by about
#: four orders of magnitude per step, so this is reached in four or five; an
#: *absolute* 1e-12 is below the last bit of a deep core level and the
#: iteration then oscillates there forever, which is why the loop also stops
#: as soon as a step fails to improve on the one before it.
ENERGY_TOLERANCE = 1e-12

#: Smallest ``M`` the square root is taken of.  ``M`` is positive wherever the
#: state has weight; this only guards the deepest grid point of a heavy atom.
MASS_FLOOR = 1e-3


# --------------------------------------------------------------------------- #
# Angular momentum bookkeeping.
# --------------------------------------------------------------------------- #

def kappa_of(l: int, j: float) -> int:
    r"""The Dirac quantum number :math:`\kappa` of ``(l, j)``."""
    l = int(l)
    if abs(j - (l + 0.5)) < 1e-9:
        return -(l + 1)
    if abs(j - (l - 0.5)) < 1e-9 and l > 0:
        return l
    raise ValueError(f"j must be l +/- 1/2 (and positive); got l={l}, j={j}")


def l_of(kappa: int) -> int:
    r"""The orbital angular momentum belonging to :math:`\kappa`."""
    kappa = int(kappa)
    if kappa == 0:
        raise ValueError("kappa = 0 is not a Dirac quantum number")
    return -kappa - 1 if kappa < 0 else kappa


def j_of(kappa: int) -> float:
    r"""The total angular momentum belonging to :math:`\kappa`."""
    return abs(int(kappa)) - 0.5


def kappa_values(l: int) -> list[int]:
    r"""The :math:`\kappa` values of a subshell, ordered by increasing ``j``.

    ``[l, -(l+1)]`` for ``l > 0`` (that is, :math:`j = l-\tfrac12` then
    :math:`j = l+\tfrac12`) and ``[-1]`` for an s shell.
    """
    l = int(l)
    return [-1] if l == 0 else [l, -(l + 1)]


def degeneracy(kappa: int) -> int:
    """``2j + 1``: how many electrons the ``(l, j)`` subshell holds."""
    return int(round(2 * j_of(kappa) + 1))


def j_average(values: dict, l: int) -> float:
    r""":math:`(2j+1)`-weighted average over the :math:`j` of one ``l``.

    ``values`` maps :math:`\kappa` to a number (an eigenvalue, a potential
    sample).  This is the combination the scalar-relativistic equation
    reproduces, and the one a spin-orbit-free pseudopotential must be built
    from.
    """
    ks = kappa_values(l)
    weights = np.array([degeneracy(k) for k in ks], dtype=float)
    data = np.array([values[k] for k in ks], dtype=float)
    return float(np.dot(weights, data) / weights.sum())


def spin_orbit_difference(values: dict, l: int) -> float:
    r"""The spin-orbit combination :math:`\frac{2}{2l+1}(X_{l+1/2}-X_{l-1/2})`.

    Zero for ``l = 0``.  This is the coefficient of :math:`\mathbf{L}\cdot
    \mathbf{S}` that reproduces the two ``j`` channels when added to the
    :func:`j_average`: with :math:`\langle\mathbf{L}\cdot\mathbf{S}\rangle =
    l/2` for :math:`j = l+\tfrac12` and :math:`-(l+1)/2` for
    :math:`j = l-\tfrac12`, the pair
    :math:`X^{\text{avg}} + X^{\text{SO}}\,\mathbf{L}\cdot\mathbf{S}` returns
    :math:`X_{l\pm1/2}` exactly.
    """
    if int(l) == 0:
        return 0.0
    up = values[-(l + 1)]        # j = l + 1/2
    down = values[l]             # j = l - 1/2
    return float(2.0 / (2 * l + 1) * (up - down))


# --------------------------------------------------------------------------- #
# The closed-form hydrogenic spectrum (the test oracle).
# --------------------------------------------------------------------------- #

def hydrogenic_dirac_energy(atomic_number: float, n: int, kappa: int,
                            c: float = SPEED_OF_LIGHT) -> float:
    r"""Exact Dirac binding energy of a one-electron ion (Hartree).

    .. math::

        \varepsilon = c^2\Bigg[
            \Big(1 + \frac{(Z/c)^2}{(n_r + \gamma)^2}\Big)^{-1/2} - 1\Bigg],
        \quad n_r = n - |\kappa|,
        \quad \gamma = \sqrt{\kappa^2 - (Z/c)^2} .

    Measured from the rest mass, so it reduces to :math:`-Z^2/2n^2` as
    :math:`c\to\infty`.  It depends on :math:`n` and :math:`j` only -- the
    Dirac degeneracy of :math:`2p_{1/2}` with :math:`2s_{1/2}`.
    """
    za = float(atomic_number) / c
    k = int(kappa)
    if abs(k) > n:
        raise ValueError(f"|kappa| = {abs(k)} exceeds n = {n}")
    if za >= abs(k):
        raise ValueError(
            f"Z/c = {za:.4f} reaches |kappa| = {abs(k)}: the point-nucleus "
            "Dirac equation has no bound state there (Z > 137 for kappa = -1)")
    gamma = np.sqrt(k * k - za * za)
    x = za * za / (n - abs(k) + gamma) ** 2
    # expm1(-log1p(x)/2) rather than (1+x)**-0.5 - 1: the binding energy is
    # the *difference* of two numbers that agree to (Z/c)^2, so the direct
    # form loses every digit of it for a light atom or a large c -- 4e-5
    # relative at Z/c = 1e-6, where the answer is still exactly -Z^2/2n^2.
    return float(c * c * np.expm1(-0.5 * np.log1p(x)))


# --------------------------------------------------------------------------- #
# The relativistic radial operator.
# --------------------------------------------------------------------------- #

def potential_derivatives(r, potential, atomic_number: float = 0.0):
    r"""``(V', V'')`` with the Coulomb singularity differentiated in closed form.

    ``potential`` is the full :math:`V`, and ``atomic_number`` says how much of
    it is the :math:`-Z/r` nuclear term; that part contributes :math:`Z/r^2`
    and :math:`-2Z/r^3` analytically and only the smooth remainder is
    differentiated on the grid.  Taking :math:`V''` numerically through the
    singularity instead costs three digits in the 1s eigenvalue of oxygen,
    because :math:`-2Z/r^3` is 1e8 at the first grid point.

    **These do not depend on the energy**, so a self-consistent atom computes
    them once per potential and reuses them across every state and every step
    of the :math:`M(\varepsilon)` iteration.
    """
    r = np.asarray(r, dtype=float)
    potential = np.asarray(potential, dtype=float)
    Z = float(atomic_number)
    smooth = potential + Z / r
    d_smooth = np.gradient(smooth, r, edge_order=2)
    d2_smooth = np.gradient(d_smooth, r, edge_order=2)
    return (Z / (r * r) + d_smooth, -2.0 * Z / (r ** 3) + d2_smooth)


def mass_factor(r, potential, energy: float, atomic_number: float = 0.0,
                c: float = SPEED_OF_LIGHT, derivatives=None):
    r"""``(M, M', M'')`` of :math:`M = 1 + (\varepsilon - V)/2c^2`.

    ``derivatives`` is an already-computed ``(V', V'')`` from
    :func:`potential_derivatives`; it is recomputed when omitted.
    """
    r = np.asarray(r, dtype=float)
    potential = np.asarray(potential, dtype=float)
    dV, d2V = (potential_derivatives(r, potential, atomic_number)
               if derivatives is None else derivatives)
    two_c2 = 2.0 * c * c
    M = 1.0 + (energy - potential) / two_c2
    return (np.maximum(M, MASS_FLOOR), -dV / two_c2, -d2V / two_c2)


def darwin_spin_orbit_term(r, potential, kappa, M, atomic_number=0.0,
                           c=SPEED_OF_LIGHT):
    r"""``kappa M'/(Mr) - M''/(2M)``, with its singular part cancelled exactly.

    Those two terms are what carry the spin-orbit and Darwin physics, and
    written separately they are a numerical trap.  Both diverge as
    :math:`1/r^3`, and their **sum does not**:

    .. math::

        \frac{\kappa M'}{Mr} - \frac{M''}{2M}
          = \frac{1}{2c^2M}\Big[\frac{V''}{2} - \frac{\kappa V'}{r}\Big]
          = \frac{1}{2c^2M}\Big[-\frac{(1+\kappa)Z}{r^3}
              + \frac{V_s''}{2} - \frac{\kappa V_s'}{r}\Big]

    for :math:`V = -Z/r + V_s`.  The factor :math:`(1+\kappa)` kills the
    :math:`1/r^3` term **identically** at :math:`\kappa = -1` -- which is
    every s state, and every state of the scalar-relativistic equation.

    Forming the difference instead subtracts two numbers that reach 4.2e6 at
    the innermost node of a 64000-point grid and agree to 5e-8, losing seven
    digits.  It gets *worse* as the grid is refined, which is why the
    valence s eigenvalues converged erratically -- their differences grew
    rather than shrank -- while every :math:`l > 0` channel, whose wave is
    suppressed where the cancellation is bad, converged cleanly at rate 4.
    """
    r = np.asarray(r, dtype=float)
    potential = np.asarray(potential, dtype=float)
    Z = float(atomic_number)
    k = int(kappa)
    smooth = potential + Z / r
    d_smooth = np.gradient(smooth, r, edge_order=2)
    d2_smooth = np.gradient(d_smooth, r, edge_order=2)
    bracket = (-(1.0 + k) * Z / r ** 3
               + 0.5 * d2_smooth
               - k * d_smooth / r)
    return bracket / (2.0 * c * c * M)


def relativistic_f(r, potential, l: int, kappa: int, energy: float,
                   atomic_number: float = 0.0, c: float = SPEED_OF_LIGHT,
                   treatment: str = "scalar"):
    r"""The Numerov coefficient of :math:`W'' = f\,W`.

    .. math::

        f = \frac{l(l+1)}{r^2} + \frac{\kappa M'}{Mr}
            - \frac{M''}{2M} + \frac{3(M')^2}{4M^2} + 2M(V - \varepsilon) ,

    which is :math:`2[V + l(l+1)/2r^2 - \varepsilon]` exactly when
    ``treatment="none"`` -- the same array
    :func:`~mandacaru.pseudopotentials.oncv._radial_f` builds.  The solution is
    :math:`W`; multiply by :math:`M^{1/2}` for :math:`P = rg`
    (:func:`large_component`).
    """
    r = np.asarray(r, dtype=float)
    potential = np.asarray(potential, dtype=float)
    key = _resolve(treatment)
    centrifugal = l * (l + 1) / (r * r)
    if key == "none":
        return centrifugal + 2.0 * (potential - energy)

    k = SCALAR_KAPPA if key == "scalar" else int(kappa)
    M, dM, _d2M = mass_factor(r, potential, energy, atomic_number, c)
    return (centrifugal
            + darwin_spin_orbit_term(r, potential, k, M, atomic_number, c)
            + 3.0 * dM * dM / (4.0 * M * M)
            + 2.0 * M * (potential - energy))


def spin_orbit_radial(r, potential, atomic_number: float = 0.0,
                      c: float = SPEED_OF_LIGHT, mass_corrected: bool = True,
                      energy: float = 0.0):
    r"""The radial spin-orbit function :math:`\xi(r)` of ``L . S``.

    .. math::

        \xi(r) = \frac{1}{2c^2 M(r)^2}\,\frac{1}{r}\,\frac{dV}{dr}

    so that :math:`H_{SO} = \xi(r)\,\mathbf{L}\cdot\mathbf{S}` reproduces
    the :math:`\kappa`-dependent term of the radial equation.  That identity
    is exact rather than a model: the only :math:`j` dependence left after
    eliminating the small component is :math:`-(M'/M)\kappa P/r`, and

    .. math::

        \kappa = -\big(2\,\langle\mathbf{L}\cdot\mathbf{S}\rangle + 1\big)

    for both :math:`j`, so the part of that term which distinguishes them is
    proportional to :math:`\mathbf{L}\cdot\mathbf{S}`.

    ``mass_corrected`` keeps the :math:`M^{-2}` factor, which matters only
    where the potential is deep; setting it to ``False`` gives the textbook
    :math:`\frac{1}{2c^2 r}\frac{dV}{dr}` that reproduces hydrogen's
    :math:`2p` fine structure, :math:`Z^4/32c^2`, in closed form.

    The Coulomb singularity is differentiated analytically through
    :func:`potential_derivatives`, so ``atomic_number`` should say how much of
    ``potential`` is :math:`-Z/r`.
    """
    r = np.asarray(r, dtype=float)
    potential = np.asarray(potential, dtype=float)
    dV, _d2V = potential_derivatives(r, potential, atomic_number)
    xi = dV / (2.0 * c * c * r)
    if mass_corrected:
        M = np.maximum(1.0 + (energy - potential) / (2.0 * c * c), MASS_FLOOR)
        xi = xi / (M * M)
    return xi


def large_component(w, M):
    r""":math:`P = M^{1/2}W` -- what the rest of the code calls ``u``."""
    return np.asarray(w, dtype=float) * np.sqrt(np.asarray(M, dtype=float))


def small_component(r, P, kappa: int, M, c: float = SPEED_OF_LIGHT):
    r""":math:`F = rf`, from :math:`F = (P' + \kappa P/r)/(2cM)`.

    Exact given :math:`P`; the derivative is taken on the grid.
    """
    r = np.asarray(r, dtype=float)
    P = np.asarray(P, dtype=float)
    dP = np.gradient(P, r, edge_order=2)
    return (dP + int(kappa) * P / r) / (2.0 * c * np.asarray(M, dtype=float))


def _resolve(treatment: str) -> str:
    key = str(treatment).strip().lower()
    aliases = {"none": "none", "nonrelativistic": "none",
               "non-relativistic": "none", "nr": "none", "schrodinger": "none",
               "scalar": "scalar", "scalar-relativistic": "scalar",
               "sr": "scalar", "koelling-harmon": "scalar", "kh": "scalar",
               "dirac": "dirac", "full": "dirac", "relativistic": "dirac"}
    if key not in aliases:
        raise ValueError(
            f"unknown relativistic treatment {treatment!r}; "
            f"available: {', '.join(TREATMENTS)}")
    return aliases[key]


#: Points of the logarithmic grid used for a relativistic eigenvalue.  1200
#: resolves what 64000 uniform points cannot; see :mod:`~.loggrid`.
LOG_GRID_POINTS = 1200


def _on_log_grid(r, potential, atomic_number, points=LOG_GRID_POINTS):
    """``(r_log, V_log)`` -- the same potential, carried onto a log grid.

    The log grid reaches decades further in than the uniform one, so ``V``
    there cannot be interpolated; it has to be *extended*.  The Coulomb part
    is known in closed form, so it is split off and the remainder -- the
    screening, which is smooth and flat at the origin -- is what gets
    interpolated, held constant inside the innermost uniform point.
    """
    from scipy.interpolate import CubicSpline
    from .loggrid import log_grid

    r = np.asarray(r, dtype=float)
    Z = float(atomic_number)
    screening = np.asarray(potential, dtype=float) + Z / r
    r_log, _x, _dx = log_grid(float(r[-1]), max(Z, 1.0), points=int(points))
    inner = r_log < r[0]
    v_s = np.empty_like(r_log)
    v_s[~inner] = CubicSpline(r, screening)(r_log[~inner])
    v_s[inner] = screening[0]
    return r_log, v_s - Z / r_log


def _log_grid_state(r, potential, l, n_nodes, kappa, key, atomic_number, c,
                    energy_guess):
    """One state solved on a log grid, splined back onto ``r``."""
    from scipy.interpolate import CubicSpline
    from .loggrid import solve_radial_log

    r_log, v_log = _on_log_grid(r, potential, atomic_number)
    P_log, eps = solve_radial_log(
        r_log, v_log, l, n_nodes, kappa=kappa, treatment=key,
        atomic_number=atomic_number, c=c, energy_guess=energy_guess)
    return _normalize(CubicSpline(r_log, P_log)(r), r), eps


def solve_radial_relativistic(r, potential, l: int, n_nodes: int,
                              kappa: int | None = None,
                              treatment: str = "scalar",
                              atomic_number: float = 0.0,
                              c: float = SPEED_OF_LIGHT,
                              max_iterations: int = 16,
                              energy_guess: float | None = None,
                              derivatives=None, grid: str = "uniform"):
    r"""Bound state of the relativistic radial equation.

    Parameters
    ----------
    r, potential : ndarray
        Uniform radial grid (Bohr, strictly positive) and :math:`V(r)` on it.
    l, n_nodes : int
        Angular momentum and the number of radial nodes wanted, ``n - l - 1``.
    kappa : int, optional
        Required for ``treatment="dirac"``; ignored otherwise.
    treatment : str
        ``"none"``, ``"scalar"`` or ``"dirac"``.
    atomic_number : float
        The :math:`Z` of the :math:`-Z/r` part of ``potential``, so the
        Coulomb singularity can be differentiated in closed form.
    grid : str
        ``"uniform"`` (the default) solves on ``r`` itself.  ``"log"`` solves
        on a logarithmic grid and splines the result back, which is far more
        accurate in the **eigenvalue** -- and is deliberately *not* the
        default; see the note below.

    Returns
    -------
    (P, eps) : (ndarray, float)
        :math:`P = rg` normalized to :math:`\int P^2 dr = 1`, positive near
        the origin, and the eigenvalue in Hartree.

    Notes
    -----
    With ``treatment="none"`` this reproduces
    :func:`~mandacaru.basis.atomic_solver.solve_radial` to machine precision --
    the same discretization, reached through the same matrix.

    Relativistically a **uniform** grid cannot converge an :math:`l=0` state:
    :math:`P \sim r^{\gamma}` with :math:`\gamma < 1` is not analytic at the
    origin, and the error of the level scales as :math:`(Z\alpha)^2` -- the
    size of the correction being computed.  ``grid="log"`` fixes that, and on
    a hydrogenic atom it is five to six orders of magnitude better; the
    non-relativistic uniform grid converges *to* the log value, which is what
    identifies the log value as the right one.  Measured on oxygen at a fixed
    converged potential, the uniform grid overstates the relativistic 1s shift
    by about a factor of three (-0.064 against -0.024 Hartree) and the 2s
    shift by about two (-0.0050 against -0.0028).

    **It is still not the default, and the reason is not caution.**  An
    accurate eigenvalue and a wave the generators can pseudize are different
    requirements.  The ONCVPSP and PAW-LCAO constructions need a wave that
    satisfies the radial equation *on the uniform grid* to fourth order --
    :func:`~mandacaru.pseudopotentials.oncv.reference_bound_state` documents
    what happens otherwise, a ghost 56 Hartree below the reference -- and they
    get it by shooting Numerov there, which is also why
    :func:`~mandacaru.basis.atomic_solver.solve_atom` finishes on Numerov
    (``polish``).  A log-grid wave splined onto ``r`` satisfies neither
    discretization's equation, and switching only the atom breaks the very
    atom-generator agreement ``polish`` exists to hold: with ``grid="log"``
    and ``polish`` both on, oxygen's relativistic total-energy shift comes out
    with the **wrong sign** (+0.083 instead of -0.056 Hartree), because the
    two are fighting over the valence levels.

    Using the log grid throughout therefore means moving the reference atom
    *and* the generators' reference shoot onto it together, and regenerating
    every dataset.  Until that is done as one deliberate change, ``"log"`` is
    the accurate reference the uniform path is measured against, not a
    drop-in replacement for it.
    """
    key = _resolve(treatment)
    if key == "dirac" and kappa is None:
        raise ValueError("treatment='dirac' needs kappa (use kappa_values(l))")
    r = np.asarray(r, dtype=float)
    potential = np.asarray(potential, dtype=float)
    step = float(r[1] - r[0])
    centrifugal = l * (l + 1) / (2.0 * r * r)

    def non_relativistic():
        diag = 1.0 / step ** 2 + potential + centrifugal
        off = -0.5 / step ** 2 * np.ones(r.size - 1)
        values, vectors = eigh_tridiagonal(diag, off, select="i",
                                           select_range=(n_nodes, n_nodes))
        return vectors[:, 0], float(values[0])

    if key == "none":
        if grid == "uniform":
            u, eps = non_relativistic()
            return _normalize(u, r), eps
        # A non-relativistic state is analytic at the origin, so the uniform
        # grid already converges at fourth order and the log grid buys little.
        # It is offered anyway because comparing across `relativity=` is only
        # meaningful when both sides share a discretization: a "relativistic
        # shift" measured between a uniform non-relativistic atom and a
        # logarithmic relativistic one is a grid difference wearing a
        # physical name.
        return _log_grid_state(r, potential, l, n_nodes, SCALAR_KAPPA,
                               "none", atomic_number, c, energy_guess)

    if energy_guess is None:
        # Seeding M with the non-relativistic level costs one extra inner
        # solve; a self-consistent atom passes the previous iteration's
        # eigenvalue instead and converges in one or two.
        _u, eps = non_relativistic()
    else:
        eps = float(energy_guess)
    if derivatives is None:
        derivatives = potential_derivatives(r, potential, atomic_number)

    k = SCALAR_KAPPA if key == "scalar" else int(kappa)

    if grid == "log":
        return _log_grid_state(r, potential, l, n_nodes, k, key,
                               atomic_number, c, eps)
    if grid != "uniform":
        raise ValueError(f"grid must be 'log' or 'uniform', not {grid!r}")

    vectors = None
    last_change = np.inf
    for _ in range(max_iterations):
        M, dM, _d2M = mass_factor(r, potential, eps, atomic_number, c,
                                  derivatives)
        # A = -d^2/dr^2 + bracket, then H = M^{-1/2} A M^{-1/2} with
        # eigenvalue 2 eps and eigenvector P.
        bracket = (2.0 * l * (l + 1) / (2.0 * r * r)
                   + darwin_spin_orbit_term(r, potential, k, M,
                                            atomic_number, c)
                   + 3.0 * dM * dM / (4.0 * M * M)
                   + 2.0 * M * potential)
        inv_sqrt = 1.0 / np.sqrt(M)
        diag = (2.0 / step ** 2 + bracket) * inv_sqrt * inv_sqrt
        off = -1.0 / step ** 2 * inv_sqrt[:-1] * inv_sqrt[1:]
        values, vectors = eigh_tridiagonal(diag, off, select="i",
                                           select_range=(n_nodes, n_nodes))
        new = 0.5 * float(values[0])
        change = abs(new - eps)
        eps = new
        if (change <= ENERGY_TOLERANCE * max(1.0, abs(new))
                or change >= last_change):
            break
        last_change = change
    return _normalize(vectors[:, 0], r), eps


def _normalize(u, r):
    u = np.asarray(u, dtype=float)
    u = u / np.sqrt(np.trapezoid(u * u, r))
    return -u if u[0] < 0 else u
