# -*- coding: utf-8 -*-
# file: examples/21_multizeta_basis.py

# This code is part of Carcará.
# MIT License
#
# Copyright (c) 2026 Leandro Seixas Rocha <leandro.rocha@ilum.cnpem.br>

r"""Multiple-zeta and polarized numerical atomic orbitals.

A single-zeta (SZ) basis gives each valence subshell exactly one radial
function, so the orbital can be occupied but never reshaped.  Two kinds of
freedom are missing, and the ``size`` argument adds them:

* **radial** -- extra *zetas*, generated by the SIESTA split-valence
  construction, let a shell contract or expand;
* **angular** -- a *polarization* shell at :math:`l+1` lets it bend, which is
  what bonding actually does to it.

.. code-block:: python

    atoms.calc = QuantumCalculator(method="vqe", basis={"name": "NAO", "size": "DZP"})

Sizes: ``SZ``, ``DZ``, ``TZ``, ``QZ``, each optionally polarized (``DZP``,
``TZ2P``, ...).  Everything is generated from scratch -- no tabulated data.

What this script measures
-------------------------
1. how many functions each size costs, per element;
2. the shape of the zeta hierarchy (each one strictly shorter-ranged);
3. the variational payoff, at Hartree-Fock, for H2;
4. the catch: extra zetas are short-ranged, so a uniform real-space grid must
   be fine enough to see them at all.

Output: ``examples/data/multizeta_basis.png``.
"""

from __future__ import annotations

import os

import numpy as np
from ase.data import atomic_numbers

from carcara.basis import BasisSet
from carcara.basis._config import valence_subshells
from carcara.basis.multizeta import zeta_tables
from carcara.basis.nao import solve_confined_radial
from carcara.basis.fao import FullAtomicOrbital
from carcara.core import MolecularIntegrals
from carcara.integrals import Grid

DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
os.makedirs(DATA, exist_ok=True)
PNG_PATH = os.path.join(DATA, "multizeta_basis.png")
RULE = "=" * 76

SIZES = ("SZ", "DZ", "DZP", "TZP", "TZ2P", "QZP")

# --------------------------------------------------------------------------- #
# 1. Basis size.
# --------------------------------------------------------------------------- #

print(RULE)
print("1. Functions per atom (each one becomes two spin orbitals => 2 qubits)")
print(RULE)
print(f"{'atom':>5}{'valence':>12}" + "".join(f"{s:>7}" for s in SIZES))
for symbol in ("H", "C", "O", "Si", "Fe"):
    shells = valence_subshells(atomic_numbers[symbol])
    label = " ".join(f"{n}{'spdf'[l]}" for n, l in shells)
    counts = "".join(f"{len(BasisSet.build('NAO', size=s).atom(symbol)):>7}"
                     for s in SIZES)
    print(f"{symbol:>5}{label:>12}{counts}")
print("\nPolarization adds one whole l+1 shell: 3 functions for an s-valence")
print("atom (H), 5 for a p-valence atom (C, O, Si), 7 for a d-valence one (Fe).")

# --------------------------------------------------------------------------- #
# 2. The zeta hierarchy.
# --------------------------------------------------------------------------- #

print(f"\n{RULE}")
print("2. The split-valence hierarchy for the hydrogen 1s")
print(RULE)

z_eff = FullAtomicOrbital.slater_effective_charge(1, 1, 0)
radius, radial, _energy = solve_confined_radial(1, 0, z_eff, 4.0, 800)
tables = zeta_tables(radius, radial, 1, 0, 4)

print(f"{'zeta':>6}{'range (a0)':>13}{'norm':>12}{'peak |R|':>12}")
for table in tables:
    support = np.nonzero(np.abs(table.values) > 1e-12)[0]
    print(f"{table.zeta:>6}{radius[support.max()]:>13.3f}"
          f"{np.trapezoid(table.values ** 2 * radius ** 2, radius):>12.3e}"
          f"{np.abs(table.values).max():>12.3f}")
print("\nEach added zeta lives strictly inside the previous one and carries")
print("less norm: it describes finer radial detail, and costs little because")
print("it vanishes early.")

# --------------------------------------------------------------------------- #
# 3. The variational payoff.
# --------------------------------------------------------------------------- #

print(f"\n{RULE}")
print("3. Hartree-Fock energy of H2 (bond 0.74 A).  More freedom cannot raise")
print("   the minimum -- the question is by how much it lowers it.")
print(RULE)


def restricted_hartree_fock(size, spacing):
    """RHF total energy of H2 in Hartree, for one basis size and grid."""
    grid = Grid(center=[0, 0, 0], box_size=6.0, h=spacing)
    basis = BasisSet.build("NAO", size=size)
    functions, nuclei = [], []
    for position in ([0, 0, -0.37], [0, 0, 0.37]):
        functions += basis.atom("H", center=position, units="angstrom")
        nuclei.append((1.0, np.asarray(position)))
    integrals = MolecularIntegrals(
        nuclei, functions, grid,
        softening=0.5 * min(grid.dx, grid.dy, grid.dz))
    energy = integrals.hartree_fock(2).electronic_energy
    return energy + integrals.nuclear_repulsion, len(functions)


SPACINGS = (0.20, 0.12)
curves = {}
print(f"{'size':>6}{'orbitals':>10}" +
      "".join(f"{f'E(h={h})':>13}{'gain':>10}" for h in SPACINGS))
for size in ("SZ", "DZ", "TZ", "DZP"):
    row, orbitals = f"{size:>6}", 0
    for spacing in SPACINGS:
        energy, orbitals = restricted_hartree_fock(size, spacing)
        curves.setdefault(spacing, {})[size] = energy
        reference = curves[spacing].get("SZ", energy)
        row += f"{energy:>13.6f}{energy - reference:>10.4f}"
    print(f"{size:>6}{orbitals:>10}" + row[6:])

print("\nDouble zeta is worth ~28 mHa at h = 0.20 A and ~32 mHa at h = 0.12 A;")
print("polarization adds a little more.  The third zeta adds almost nothing")
print("here -- not because it is redundant, but because of point 4.")

# --------------------------------------------------------------------------- #
# 4. The catch: grid resolution.
# --------------------------------------------------------------------------- #

print(f"\n{RULE}")
print("4. Why the third zeta is nearly free of effect on a coarse grid")
print(RULE)
BOHR_TO_ANGSTROM = 0.529177210903
for table in tables[1:]:
    support = np.nonzero(np.abs(table.values) > 1e-12)[0]
    extent = radius[support.max()] * BOHR_TO_ANGSTROM
    print(f"  zeta {table.zeta}: extends to {extent:.2f} A"
          f"  -> {extent / 0.20:>4.1f} grid points at h = 0.20 A,"
          f"{extent / 0.12:>5.1f} at h = 0.12 A")
print("\nA function two or three grid points wide is not represented, it is")
print("aliased.  High zetas need a fine grid; on a uniform real-space mesh")
print("that is the binding constraint, not the basis.")

# --------------------------------------------------------------------------- #
# 5. Plot.
# --------------------------------------------------------------------------- #

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:                                     # pragma: no cover
    raise SystemExit("matplotlib is not installed; the tables were still printed")

fig, (left, right) = plt.subplots(1, 2, figsize=(12.0, 4.8))

colors = ("#0072B2", "#D55E00", "#009E73", "#CC79A7")
for table, color in zip(tables, colors):
    left.plot(radius, table.values, lw=2.0, color=color,
              label=f"zeta {table.zeta}")
left.set_xlim(0.0, 4.0)
left.axhline(0.0, color="0.75", lw=0.8)
left.set_xlabel("r (Bohr)")
left.set_ylabel("R(r)")
left.set_title("Split-valence hierarchy, H 1s\n"
               "each zeta strictly shorter-ranged")
left.legend(frameon=False)

order = ("SZ", "DZ", "TZ", "DZP")
width = 0.38
positions = np.arange(len(order))
for offset, spacing in enumerate(SPACINGS):
    gains = [1000.0 * (curves[spacing]["SZ"] - curves[spacing][s])
             for s in order]
    right.bar(positions + (offset - 0.5) * width, gains, width,
              label=f"h = {spacing} A",
              color=("#0072B2", "#D55E00")[offset])
right.set_xticks(positions)
right.set_xticklabels(order)
right.set_ylabel("energy lowering vs SZ (mHa)")
right.set_title("Variational payoff, H2 at Hartree-Fock\n"
                "(higher is better)")
right.legend(frameon=False)

for axis in (left, right):
    axis.grid(True, axis="y", color="0.92", lw=0.8)
    for spine in ("top", "right"):
        axis.spines[spine].set_visible(False)

fig.tight_layout()
fig.savefig(PNG_PATH, dpi=150)
print(f"\nwrote {PNG_PATH}")
print(RULE)
