# -*- coding: utf-8 -*-
# file: src/mandacaru/algorithms/basis_report.py

# This code is part of Mandacaru.
# MIT License
#
# Copyright (c) 2026 Leandro Seixas Rocha <leandro.rocha@ilum.cnpem.br>

"""What the ``[BASIS]`` block of a run log says.

A basis here is *built* at run time -- the size hierarchy, the confinement, the
Fourier filter are options, not files -- so the options a user typed are not a
record of the basis that ran: the defaults they left alone (a PAW basis is
filtered unless told otherwise), the radii an ``energy_shift`` resolved to and
the dataset each element was read from are all decided below the calculator.
This module collects them from the Hamiltonian builder's ``context`` into the
two things a log block is made of: keyed ``fields`` and named ``tables``.

It is the record a comparison against another code is made from (the same
``size`` and ``energy_shift`` in GPAW, say), so it reports what was *used*:
every orbital's cutoff radius and the eigenvalue shift actually achieved, not
the number that was asked for.
"""

from __future__ import annotations

import numpy as np

from ..units import BOHR_TO_ANGSTROM, HARTREE_TO_EV

#: The exchange-correlation functional of the atomic reference calculations.
#: Every family is generated by the LDA radial solver; it enters the datasets
#: only -- the molecular Hamiltonian has the bare Coulomb interaction.
DATASET_XC = "LDA"


def _counts(symbols, atom_of_orbital):
    """Basis functions per element, ``{symbol: functions on one atom}``."""
    per_atom = np.bincount(np.asarray(atom_of_orbital, dtype=int),
                           minlength=len(symbols))
    out = {}
    for symbol, count in zip(symbols, per_atom):
        out.setdefault(symbol, int(count))
    return out


def _option_text(value) -> str:
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k}: {_option_text(v)}"
                               for k, v in sorted(value.items())) + "}"
    return str(value)


def _per_element(spec, symbol, default):
    """One element's value of an option that may be ``{symbol: value}``."""
    if isinstance(spec, dict):
        table = {(k if k == "*" else str(k).capitalize()): v
                 for k, v in spec.items()}
        spec = table.get(symbol.capitalize(), table.get("*"))
    return default if spec is None else spec


def _pseudo_report(name, context, symbols, fields, tables):
    from ..basis.filtering import cutoff_energy_ev, filter_label
    from ..basis.multizeta import DEFAULT_SPLIT_NORM, resolve_zeta
    from ..pseudopotentials.confinement import (energy_shift_label,
                                                resolve_polarization,
                                                validate_confinement)
    from ..pseudopotentials.families import (pseudo_basis_arguments,
                                             resolve_family)

    family = resolve_family(context["family"])
    options = dict(context.get("options") or {})
    potentials = context["pseudopotentials"]
    integrals = context["integrals"]

    fields["family"] = f"{family.label} ({family.description})"
    fields["size"] = _option_text(options.get("size", "SZ"))
    # Which split-valence scheme built the extra zetas.  The two are not
    # comparable digit for digit (a tail *norm* of 0.16 is a squared-norm
    # fraction of 0.0256), so the line names the scheme, not just a number.
    tail_norms = pseudo_basis_arguments(family.name, options).get("tail_norms")
    if tail_norms is not None:
        fields["zeta_split"] = (
            "tail_norm " + ", ".join(f"{t:g}" for t in tail_norms)
            + " (norm of the tail, every zeta split from the first)")
    else:
        fields["zeta_split"] = (
            "split_norm " + _option_text(options.get("split_norm")
                                         or DEFAULT_SPLIT_NORM)
            + " (squared norm of the tail, each zeta split from the previous"
              " one, halved per zeta)")
    if "projector_basis" in family.options:
        from ..pseudopotentials.paw import DEFAULT_PROJECTOR_BASIS
        fields["projector_basis"] = options.get("projector_basis",
                                                DEFAULT_PROJECTOR_BASIS)

    # Confinement: what was asked, and the potential it was applied with.
    if "energy_shift" in family.options:
        # The label reads "energy_shift 0.1 eV"; the key already says so.
        fields["energy_shift"] = energy_shift_label(
            options.get("energy_shift")).removeprefix("energy_shift ")
        if context.get("confinement"):
            amplitude, inner = validate_confinement(options.get("confinement"))
            fields["confinement_potential"] = (
                f"A exp(-(r_c - r_i)/(r - r_i)) / (r_c - r), "
                f"A = {amplitude:g} Ha, r_i = {inner:g} r_c")
        kind = resolve_polarization(options.get("polarization"),
                                    options.get("energy_shift"))
        fields["polarization"] = (
            "gaussian (quasi-Gaussian: r^l [exp(-r^2/r_char^2) - "
            "(a - b r^2)], further shells split from it)"
            if kind == "gaussian" else
            "orbital (r^k R_outer(r), one shell per added l)")

    # The filter: the option, and the cutoff the grid resolved it to.
    fields["filter"] = filter_label(options.get("filter"))
    k_c = context.get("filter_cutoff")
    if k_c is not None:
        fields["filter_cutoff"] = (f"{k_c:.4f} Bohr^-1 "
                                   f"({cutoff_energy_ev(k_c):.2f} eV)")

    # How the local potential is integrated (PAW's range separation).
    if getattr(integrals, "split_local_potential", False):
        fields["local_potential"] = (
            "range-separated: long range on the grid, short range on "
            "atom-centered quadrature (sigma = "
            f"{integrals.local_split_width():.4f} Bohr)")
    else:
        fields["local_potential"] = "real-space grid"
    fields["dataset_xc"] = (f"{DATASET_XC} (atomic reference only; the "
                            "valence interaction is the bare Coulomb operator)")

    datasets = [("symbol", "Z", "Z_ion", "l_max", "r_cut_Bohr", "source")]
    for symbol in sorted(set(symbols), key=symbols.index):
        pp = potentials[symbol]
        r_cut = max(float(c.r_cut) for c in pp.channels.values())
        datasets.append((
            symbol, int(round(float(getattr(pp, "atomic_number", 0) or 0))),
            f"{float(pp.valence_charge):g}", max(pp.channels),
            f"{r_cut:.4f}",
            str(getattr(pp, "source", "generated-in-memory")).replace(" ", "_")))
    tables["datasets"] = datasets

    confined = context.get("confinement") or {}
    orbitals = [("symbol", "l", "zetas", "polarization", "r_c_Bohr",
                 "r_c_Angstrom", "eps_free_eV", "eps_basis_eV", "shift_eV")]
    for symbol in sorted(set(symbols), key=symbols.index):
        pp = potentials[symbol]
        n_zeta, n_polarization = resolve_zeta(
            _per_element(options.get("size"), symbol, "SZ"))
        l_max = max(pp.channels)
        for l in sorted(pp.channels):
            orbital = confined.get(symbol, {}).get(int(l))
            channel = pp.channels[l]
            energies = (getattr(channel, "reference_energies", None)
                        or [getattr(channel, "energy", float("nan"))])
            free = float(energies[0]) * HARTREE_TO_EV
            polarization = n_polarization if l == l_max else 0
            if orbital is None:
                row = ("unconfined", "unconfined", f"{free:.6f}",
                       f"{free:.6f}", "0.000000")
            else:
                row = (f"{orbital.r_c:.4f}",
                       f"{orbital.r_c * BOHR_TO_ANGSTROM:.4f}",
                       f"{free:.6f}", f"{orbital.energy * HARTREE_TO_EV:.6f}",
                       f"{orbital.achieved_shift:.6f}")
            orbitals.append((symbol, l, n_zeta, polarization) + row)
    tables["orbitals"] = orbitals

    shells = context.get("polarization") or {}
    if shells:
        tables["polarization_shells"] = (
            [("symbol", "l", "based_on_l", "r_cut_Bohr", "r_char_Bohr",
              "r_c_at_0.3eV_Bohr")]
            + [(symbol, shell.l, shell.base_l, f"{shell.r_cut:.4f}",
                f"{shell.r_char:.4f}", f"{shell.reference_radius:.4f}")
               for symbol, shell in shells.items()])


def basis_report(basis, context, symbols) -> tuple[dict, dict]:
    """``(fields, tables)`` of the ``[BASIS]`` block.

    ``basis`` is the driver's ``basis`` argument, ``context`` what the
    Hamiltonian builder returned, ``symbols`` the geometry's chemical symbols.
    Each table is a list of rows whose first row is the column names; cells
    never contain spaces, so a reader splits a row on whitespace.
    """
    from ._hamiltonian_from_atoms import PER_ELEMENT, resolve_basis

    symbols = list(symbols)
    fields: dict = {}
    tables: dict = {}
    name, options = resolve_basis(basis)
    fields["name"] = "per-element" if name == PER_ELEMENT else str(name)

    if context.get("family") is not None:
        _pseudo_report(name, context, symbols, fields, tables)
    else:
        fields["family"] = "all-electron"
        if options:
            fields["options"] = _option_text(options)
        integrals = context.get("integrals")
        softening = getattr(getattr(integrals, "_potentials", None),
                            "softening", None)
        if softening:
            fields["nuclear_cusp_softening"] = f"{float(softening):.4f} Bohr"

    counts = _counts(symbols, context["atom_of_orbital"])
    fields["basis_functions"] = int(len(context["atom_of_orbital"]))
    frozen = tuple(context.get("frozen") or ())
    if frozen:
        fields["frozen_orbitals"] = f"{len(frozen)} {list(frozen)}"
    tables["functions"] = ([("symbol", "atoms", "functions_per_atom")]
                           + [(symbol, symbols.count(symbol), count)
                              for symbol, count in counts.items()])
    return fields, tables
